export const FETCH_ADMIN_ORDERS_REQUEST = 'FETCH_ADMIN_ORDERS_REQUEST';
export const FETCH_ADMIN_ORDERS_SUCCESS = 'FETCH_ADMIN_ORDERS_SUCCESS';
export const FETCH_ADMIN_ORDERS_FAILURE = 'FETCH_ADMIN_ORDERS_FAILURE';

export const UPDATE_ADMIN_ORDER_STATUS_REQUEST = 'UPDATE_ADMIN_ORDER_STATUS_REQUEST';
export const UPDATE_ADMIN_ORDER_STATUS_SUCCESS = 'UPDATE_ADMIN_ORDER_STATUS_SUCCESS';
export const UPDATE_ADMIN_ORDER_STATUS_FAILURE = 'UPDATE_ADMIN_ORDER_STATUS_FAILURE';

export const FETCH_ADMIN_CARTS_REQUEST = 'FETCH_ADMIN_CARTS_REQUEST';
export const FETCH_ADMIN_CARTS_SUCCESS = 'FETCH_ADMIN_CARTS_SUCCESS';
export const FETCH_ADMIN_CARTS_FAILURE = 'FETCH_ADMIN_CARTS_FAILURE';
